
version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: e6cache
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - dev_db_data:/var/lib/postgresql/data
      - ../db.sql:/docker-entrypoint-initdb.d/init.sql:ro

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console UI
    volumes:
      - dev_minio_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: 
      - /bin/sh
      - -c
      - |
        echo "Waiting for MinIO to be ready..."
        until /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin; do
          echo "MinIO not ready yet, retrying in 2s..."
          sleep 2
        done
        /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
        /usr/bin/mc mb minio/e6cache-media --ignore-existing;
        exit 0;

volumes:
  dev_db_data:
  dev_minio_data:
