name: Upload Go test results
# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-go
on: [push]
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24.3' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
        working-directory: ./src
      - name: Test with Go
        run: go test -json > TestResults-${{ matrix.go-version }}.json
        working-directory: ./src
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: src/TestResults-${{ matrix.go-version }}.json
